In [1]:
import pandas as pd
import numpy as np

print("Notebook works")

Notebook works

In [2]:
from pathlib import Path

In [3]:
project_root = Path.cwd().parent
project_root

WindowsPath('C:/Users/angel/PycharmProjects/football-analytics')

In [4]:
file_path = project_root / "data" / "raw" / "matches.csv"
df = pd.read_csv(file_path)

C:\Users\angel\AppData\Local\Temp\ipykernel_21628\1078144437.py:2: DtypeWarning: Columns (0: MatchTime) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [5]:
df.head()

,Division,MatchDate,MatchTime,HomeTeam,AwayTeam,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,...,MaxUnder25,HandiSize,HandiHome,HandiAway,C_LTH,C_LTA,C_VHD,C_VAD,C_HTB,C_PHB
0,F1,2000-07-28,NaN,Marseille,Troyes,1686.34,1586.57,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,F1,2000-07-28,NaN,Paris SG,Strasbourg,1714.89,1642.51,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,F2,2000-07-28,NaN,Wasquehal,Nancy,1465.08,1633.80,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,F1,2000-07-29,NaN,Auxerre,Sedan,1635.58,1624.22,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,F1,2000-07-29,NaN,Bordeaux,Metz,1734.34,1673.11,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.shape

(230557, 48)

In [7]:
df.columns.tolist()

['Division',
 'MatchDate',
 'MatchTime',
 'HomeTeam',
 'AwayTeam',
 'HomeElo',
 'AwayElo',
 'Form3Home',
 'Form5Home',
 'Form3Away',
 'Form5Away',
 'FTHome',
 'FTAway',
 'FTResult',
 'HTHome',
 'HTAway',
 'HTResult',
 'HomeShots',
 'AwayShots',
 'HomeTarget',
 'AwayTarget',
 'HomeFouls',
 'AwayFouls',
 'HomeCorners',
 'AwayCorners',
 'HomeYellow',
 'AwayYellow',
 'HomeRed',
 'AwayRed',
 'OddHome',
 'OddDraw',
 'OddAway',
 'MaxHome',
 'MaxDraw',
 'MaxAway',
 'Over25',
 'Under25',
 'MaxOver25',
 'MaxUnder25',
 'HandiSize',
 'HandiHome',
 'HandiAway',
 'C_LTH',
 'C_LTA',
 'C_VHD',
 'C_VAD',
 'C_HTB',
 'C_PHB']

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 230557 entries, 0 to 230556
Data columns (total 48 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Division     230557 non-null  str
 1   MatchDate    230557 non-null  str
 2   MatchTime    99072 non-null   str
 3   HomeTeam     230557 non-null  str
 4   AwayTeam     230557 non-null  str
 5   HomeElo      141597 non-null  float64
 6   AwayElo      141528 non-null  float64
 7   Form3Home    229057 non-null  float64
 8   Form5Home    229057 non-null  float64
 9   Form3Away    229057 non-null  float64
 10  Form5Away    229057 non-null  float64
 11  FTHome       230554 non-null  float64
 12  FTAway       230554 non-null  float64
 13  FTResult     230554 non-null  str
 14  HTHome       175977 non-null  float64
 15  HTAway       175977 non-null  float64
 16  HTResult     175977 non-null  str
 17  HomeShots    114735 non-null  float64
 18  AwayShots    114738 non-null  float64
 19  HomeTarget   113929 non-null  float64
 20  AwayTarget   113932 non-null  float64
 21  HomeFouls    113973 non-null  float64
 22  AwayFouls    113973 non-null  float64
 23  HomeCorners  114363 non-null  float64
 24  AwayCorners  114363 non-null  float64
 25  HomeYellow   119298 non-null  float64
 26  AwayYellow   119299 non-null  float64
 27  HomeRed      119299 non-null  float64
 28  AwayRed      119297 non-null  float64
 29  OddHome      227527 non-null  float64
 30  OddDraw      227527 non-null  float64
 31  OddAway      227527 non-null  float64
 32  MaxHome      202922 non-null  float64
 33  MaxDraw      202922 non-null  float64
 34  MaxAway      202922 non-null  float64
 35  Over25       148398 non-null  float64
 36  Under25      148397 non-null  float64
 37  MaxOver25    148398 non-null  float64
 38  MaxUnder25   148397 non-null  float64
 39  HandiSize    156733 non-null  float64
 40  HandiHome    156475 non-null  float64
 41  HandiAway    156451 non-null  float64
 42  C_LTH        112602 non-null  float64
 43  C_LTA        112602 non-null  float64
 44  C_VHD        112602 non-null  float64
 45  C_VAD        112602 non-null  float64
 46  C_HTB        112602 non-null  float64
 47  C_PHB        112602 non-null  float64
dtypes: float64(41), str(7)
memory usage: 84.4 MB

In [10]:
df.isna().sum().sort_values(ascending=False)

MatchTime      131485
C_LTA          117955
C_VHD          117955
C_VAD          117955
C_LTH          117955
C_HTB          117955
C_PHB          117955
HomeTarget     116628
AwayTarget     116625
HomeFouls      116584
AwayFouls      116584
HomeCorners    116194
AwayCorners    116194
HomeShots      115822
AwayShots      115819
AwayRed        111260
HomeYellow     111259
AwayYellow     111258
HomeRed        111258
AwayElo         89029
HomeElo         88960
MaxUnder25      82160
Under25         82160
MaxOver25       82159
Over25          82159
HandiAway       74106
HandiHome       74082
HandiSize       73824
HTHome          54580
HTResult        54580
HTAway          54580
MaxAway         27635
MaxHome         27635
MaxDraw         27635
OddHome          3030
OddAway          3030
OddDraw          3030
Form3Home        1500
Form5Home        1500
Form3Away        1500
Form5Away        1500
FTAway              3
FTHome              3
FTResult            3
HomeTeam            0
MatchDate           0
Division            0
AwayTeam            0
dtype: int64

In [11]:
df["Division"].value_counts().head(30)

Division
E1     13606
E2     13220
E3     12777
SP2    10497
I2      9921
E0      9410
I1      9012
SP1     9008
F1      8756
F2      8677
D1      7522
T1      7458
N1      7288
D2      7161
EC      7134
P1      6626
B1      6559
ARG     5330
USA     5233
SC0     5124
BRA     4850
G1      4128
SC1     4094
SC2     4092
JAP     4089
MEX     4080
SC3     4010
ROM     3640
POL     3567
SWE     3110
Name: count, dtype: int64

In [12]:
df["MatchDate"].min(), df["MatchDate"].max()

('2000-07-28', '2025-06-01')

In [13]:
df["FTResult"].value_counts(dropna=False)

FTResult
H      102873
A       66560
D       61121
NaN         3
Name: count, dtype: int64

In [14]:
clean_path = project_root / "data" / "processed" / "matches_v1_clean.csv"
clean_df = pd.read_csv(clean_path)
clean_df.head()

,match_id,division,match_date,home_team,away_team,home_elo,away_elo,form3_home,form5_home,form3_away,...,ft_away,ft_result,odd_home,odd_draw,odd_away,home_win,draw,away_win,total_goals,over_2_5
0,1,E0,2015-01-01,Aston Villa,Crystal Palace,1618.71,1607.67,2.0,5.0,1.0,...,0.0,D,2.40,3.30,3.30,0,1,0,0.0,0
1,2,E0,2015-01-01,Hull,Everton,1575.98,1758.46,3.0,4.0,0.0,...,0.0,H,3.40,3.40,2.30,1,0,0,2.0,0
2,3,E0,2015-01-01,Liverpool,Leicester,1802.87,1593.65,7.0,8.0,3.0,...,2.0,D,1.40,5.00,9.00,0,1,0,4.0,1
3,4,E0,2015-01-01,Man City,Sunderland,1945.55,1646.37,7.0,13.0,4.0,...,2.0,H,1.22,7.00,15.00,1,0,0,5.0,1
4,5,E0,2015-01-01,Newcastle,Burnley,1667.12,1592.34,3.0,6.0,1.0,...,3.0,D,1.83,3.75,4.75,0,1,0,6.0,1

In [16]:
clean_df.shape

(18943, 22)

In [17]:
clean_df["division"].value_counts()

division
SP1    4021
I1     4019
E0     3988
F1     3702
D1     3213
Name: count, dtype: int64

In [18]:
clean_df["ft_result"].value_counts(normalize=True)

ft_result
H    0.44201
A    0.30766
D    0.25033
Name: proportion, dtype: float64

In [19]:
clean_df.isna().sum().sort_values(ascending=False).head(20)

match_id      0
division      0
match_date    0
home_team     0
away_team     0
home_elo      0
away_elo      0
form3_home    0
form5_home    0
form3_away    0
form5_away    0
ft_home       0
ft_away       0
ft_result     0
odd_home      0
odd_draw      0
odd_away      0
home_win      0
draw          0
away_win      0
dtype: int64